//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 04:29:22 PM CDT 
//


package mx.jmgs.dynamicformsbase.dyna.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Separator_QNAME = new QName("http://www.dynamicforms.mx/dynaform-1.0", "separator");
    private final static QName _Label_QNAME = new QName("http://www.dynamicforms.mx/dynaform-1.0", "label");
    private final static QName _Dynaform_QNAME = new QName("http://www.dynamicforms.mx/dynaform-1.0", "dynaform");
    private final static QName _FormElement_QNAME = new QName("http://www.dynamicforms.mx/dynaform-1.0", "formElement");
    private final static QName _Field_QNAME = new QName("http://www.dynamicforms.mx/dynaform-1.0", "field");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DynamicForm }
     * 
     */
    public DynamicForm createDynaform() {
        return new DynamicForm();
    }

    /**
     * Create an instance of {@link FieldSelectItem }
     * 
     */
    public FieldSelectItem createSelectItem() {
        return new FieldSelectItem();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link FormSeparator }
     * 
     */
    public FormSeparator createSeparator() {
        return new FormSeparator();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormSeparator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dynamicforms.mx/dynaform-1.0", name = "separator", substitutionHeadNamespace = "http://www.dynamicforms.mx/dynaform-1.0", substitutionHeadName = "formElement")
    public JAXBElement<FormSeparator> createSeparator(FormSeparator value) {
        return new JAXBElement<FormSeparator>(_Separator_QNAME, FormSeparator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Label }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dynamicforms.mx/dynaform-1.0", name = "label", substitutionHeadNamespace = "http://www.dynamicforms.mx/dynaform-1.0", substitutionHeadName = "formElement")
    public JAXBElement<Label> createLabel(Label value) {
        return new JAXBElement<Label>(_Label_QNAME, Label.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DynamicForm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dynamicforms.mx/dynaform-1.0", name = "dynaform")
    public JAXBElement<DynamicForm> createDynaform(DynamicForm value) {
        return new JAXBElement<DynamicForm>(_Dynaform_QNAME, DynamicForm.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dynamicforms.mx/dynaform-1.0", name = "formElement")
    public JAXBElement<FormElement> createFormElement(FormElement value) {
        return new JAXBElement<FormElement>(_FormElement_QNAME, FormElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Field }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dynamicforms.mx/dynaform-1.0", name = "field", substitutionHeadNamespace = "http://www.dynamicforms.mx/dynaform-1.0", substitutionHeadName = "formElement")
    public JAXBElement<Field> createField(Field value) {
        return new JAXBElement<Field>(_Field_QNAME, Field.class, null, value);
    }

}
