//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 04:29:22 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dynamicforms.mx/dynaform-1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mx.jmgs.dynamicformsbase.dyna.xml;
