//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 05:07:01 PM CDT 
//


package mx.jmgs.dynamicformsbase.dyna.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for row complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="row">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.dynamicforms.mx/dynaform-1.0}formElement" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "row", propOrder = {
    "formElement"
})
public class Row {

    @XmlElementRef(name = "formElement", required=true,  namespace = "http://www.dynamicforms.mx/dynaform-1.0", type = JAXBElement.class)
    protected List<JAXBElement<FormElement>> formElement;

    /**
     * Gets the value of the formElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormElement }
     * 
     * 
     */
    public List<JAXBElement<FormElement>> getFormElements() {
        if (formElement == null) {
            formElement = new ArrayList<JAXBElement<FormElement>>();
        }
        return this.formElement;
    }

}
